spring:
  application:
    name: ws-user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_local
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ws-user-management
    show-sql: false
  flyway:
    enabled: true
    schemas: ws-user-management
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    baseline-version: 1

server:
  port: 18762
  servlet:
    encoding:
      force: true
      charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true

jwt:
  public:
    key: ${JWT_PUBLIC_SECRET_KEY}
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 36000000

auth:
  rest:
    authUrl: ${AUTH_URL}/v1/workers/auth/login
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}
feign:
  ws-auth:
    url: ${AUTH_URL}
  ws-notification:
    url: ${NOTIFICATION_URL}

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.workers.wsusermanagement: DEBUG
